"""Edge Forge — consented, auditable LoRA fine-tuning.

Trains a Llama-3-8B-Instruct LoRA on Delaware wholesale assignment contracts
(generated by synthetic_lawyer.py) using unsloth's 2x-faster 4-bit pipeline,
then exports a quantized .gguf for edge inference via llama.cpp / vLLM.

The resulting adapter is one "state lobe" — hot-swapped at inference time by
EdgeUnderwriter.hot_swap_state_lora() in local_vllm_adapter.py.

Usage:
    python -m backend.ml_forge.edge_forge.train_lora --state DE

Requires (install into the ml_forge venv, GPU recommended):
    pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
    pip install --no-deps trl peft accelerate bitsandbytes
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Mapping

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #
BASE_MODEL = "unsloth/llama-3-8b-Instruct-bnb-4bit"
MAX_SEQ_LENGTH = 4096
LOAD_IN_4BIT = True

# LoRA — adapt only the attention projections, per the edge-forge spec.
LORA_RANK = 16
LORA_ALPHA = 16
TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "o_proj"]

_FORGE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_DATA_PATH = os.path.join(_FORGE_ROOT, "output", "de_assignment_contracts.jsonl")
OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))

# Quantization method for the exported GGUF (q4_k_m balances size/quality).
GGUF_QUANT_METHOD = "q4_k_m"

SYSTEM_PROMPT = (
    "You are an edge underwriting agent for U.S. real estate wholesale deals. "
    "Given raw property data and distress signals, predict the After Repair "
    "Value (ARV), estimate rehab, apply the 70% rule to compute the Maximum "
    "Allowable Offer (MAO = 0.70 * ARV - rehab), and return a Proceed / Reject "
    "verdict as strict JSON."
)

# Style examples are only eligible after explicit opt-in and deterministic PII
# redaction.  The raw example is never written by this module.
_EMAIL_RE = re.compile(r"\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b", re.I)
_PHONE_RE = re.compile(r"(?<!\d)(?:\+?1[ .-]?)?(?:\(?\d{3}\)?[ .-]?)\d{3}[ .-]?\d{4}(?!\d)")
_SSN_RE = re.compile(r"(?<!\d)\d{3}-\d{2}-\d{4}(?!\d)")
_ADDRESS_RE = re.compile(
    r"\b\d{1,6}\s+[A-Za-z0-9.' -]{2,60}\s+(?:Street|St|Avenue|Ave|Road|Rd|Lane|Ln|Drive|Dr|Boulevard|Blvd)\b",
    re.I,
)


def redact_pii(text: str) -> tuple[str, dict[str, int]]:
    """Redact common direct identifiers and return a scan summary."""
    value = str(text or "")
    counts: dict[str, int] = {}
    for label, pattern in (
        ("email", _EMAIL_RE),
        ("phone", _PHONE_RE),
        ("ssn", _SSN_RE),
        ("street_address", _ADDRESS_RE),
    ):
        value, count = pattern.subn(f"[{label.upper()}_REDACTED]", value)
        counts[label] = count
    return value, counts


def _example_hash(agent_id: str, redacted_input: str, redacted_output: str) -> str:
    blob = json.dumps(
        {
            "agent_id": agent_id,
            "input": redacted_input,
            "output": redacted_output,
        },
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()


def prepare_consented_style_dataset(
    examples: Iterable[Mapping[str, Any]],
    *,
    agent_id: str,
    consent_version: str,
    output_path: str | os.PathLike[str],
) -> dict[str, Any]:
    """Write a redacted train/evaluation JSONL dataset and return its manifest.

    Every row must carry ``consented=True``.  Split assignment is hash-based so
    reruns are stable and evaluation examples cannot leak into training.
    """
    if not agent_id or not consent_version:
        raise ValueError("agent_id and consent_version are required")
    rows: list[dict[str, Any]] = []
    total_redactions = {"email": 0, "phone": 0, "ssn": 0, "street_address": 0}
    for index, example in enumerate(examples):
        if example.get("consented") is not True:
            raise ValueError(f"example {index} is not explicitly consented")
        redacted_input, input_scan = redact_pii(str(example.get("input") or ""))
        redacted_output, output_scan = redact_pii(str(example.get("output") or ""))
        if not redacted_input or not redacted_output:
            raise ValueError(f"example {index} is missing input or output")
        digest = _example_hash(agent_id, redacted_input, redacted_output)
        split = "evaluation" if int(digest[:8], 16) % 5 == 0 else "train"
        scan = {
            key: input_scan.get(key, 0) + output_scan.get(key, 0)
            for key in total_redactions
        }
        for key, count in scan.items():
            total_redactions[key] += count
        rows.append(
            {
                "agent_id": agent_id,
                "consent_version": consent_version,
                "example_sha256": digest,
                "split": split,
                "pii_scan": scan,
                "messages": [
                    {"role": "user", "content": redacted_input},
                    {"role": "assistant", "content": redacted_output},
                ],
            }
        )
    if len(rows) < 5:
        raise ValueError("at least five consented examples are required")
    if not any(row["split"] == "evaluation" for row in rows):
        # Stable fallback for very small eligible sets.
        rows[-1]["split"] = "evaluation"

    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, sort_keys=True, separators=(",", ":")) + "\n")

    checksum = artifact_sha256(destination)
    return {
        "agent_id": agent_id,
        "consent_version": consent_version,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "record_count": len(rows),
        "train_count": sum(row["split"] == "train" for row in rows),
        "evaluation_count": sum(row["split"] == "evaluation" for row in rows),
        "redactions": total_redactions,
        "dataset_path": str(destination),
        "dataset_sha256": checksum,
    }


def artifact_sha256(path: str | os.PathLike[str]) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def build_model_card(
    *,
    name: str,
    base_model: str,
    dataset_manifest: Mapping[str, Any],
    metrics: Mapping[str, Any],
    limitations: Iterable[str],
) -> dict[str, Any]:
    return {
        "name": name,
        "base_model": base_model,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "dataset": dict(dataset_manifest),
        "metrics": dict(metrics),
        "intended_use": "Agent-approved tone and formatting preferences only.",
        "prohibited_use": [
            "personality or distress profiling",
            "protected-class inference",
            "autonomous legal, financial, outreach, or bidding decisions",
        ],
        "limitations": list(limitations),
        "rollback_supported": True,
    }

# --------------------------------------------------------------------------- #
# Underwriting model — the synthetic contract records carry deal economics but
# no explicit ARV / rehab / distress fields, so we derive defensible training
# targets from the real property facts. Rough DE resale comps ($/sqft) by
# county feed the ARV estimate.
# --------------------------------------------------------------------------- #
_CURRENT_YEAR = datetime.now().year
_COUNTY_PPSF = {"New Castle": 215.0, "Kent": 175.0, "Sussex": 235.0}
_DEFAULT_PPSF = 200.0
_MAO_RULE = 0.70  # the wholesaler's classic 70% rule


def _round_k(value: float) -> int:
    """Round to the nearest $1,000 — how underwriters actually quote numbers."""
    return int(round(value / 1000.0) * 1000)


def _distress_signals(prop: dict, contract: dict) -> list:
    """Synthesize the deal's distress signals from the property facts. These are
    the *inputs* the model conditions on; the rehab estimate below is causally
    driven by them so the learned chain is internally consistent."""
    signals = []
    year = int(prop.get("year_built") or 0)
    age = _CURRENT_YEAR - year if year else 0

    if age >= 40:
        signals.append(f"Built {year} (~{age}y): roof/HVAC/electrical likely end-of-life")
    elif age >= 25:
        signals.append(f"Built {year} (~{age}y): aging mechanicals, dated finishes")

    contingencies = contract.get("contingencies") or []
    if "inspection" in contingencies:
        signals.append("Inspection contingency active — undisclosed condition risk")

    purchase = float(contract.get("purchase_price") or 0)
    earnest = float(contract.get("earnest_money") or 0)
    if purchase and earnest / purchase < 0.03:
        signals.append("Thin earnest deposit (<3%) — motivated/distressed seller")

    if not signals:
        signals.append("No major distress flags — standard cosmetic turnaround assumed")
    return signals


def _underwrite(record: dict) -> dict:
    """Derive the ARV / rehab / MAO / verdict target for one record."""
    prop = record.get("property") or {}
    contract = record.get("original_contract") or {}

    sqft = float(prop.get("sqft") or 0)
    county = prop.get("county", "")
    year = int(prop.get("year_built") or 0)
    age = _CURRENT_YEAR - year if year else 30
    purchase_price = float(contract.get("purchase_price") or 0)

    ppsf = _COUNTY_PPSF.get(county, _DEFAULT_PPSF)
    arv = _round_k(sqft * ppsf)

    # Rehab budget: $25/sqft cosmetic base, escalated by age-driven distress.
    rehab_psf = 25.0
    if age >= 40:
        rehab_psf += 20.0   # full systems replacement
    elif age >= 25:
        rehab_psf += 10.0   # partial mechanicals + finishes
    if "inspection" in (contract.get("contingencies") or []):
        rehab_psf += 5.0    # contingency reserve for the unknown
    rehab = _round_k(sqft * rehab_psf)

    mao = _round_k(_MAO_RULE * arv - rehab)
    spread = mao - int(purchase_price)
    verdict = "Proceed" if purchase_price and purchase_price <= mao else "Reject"

    # Exactly the 6-key schema the inference engine enforces via guided decoding
    # (local_vllm_adapter.UNDERWRITE_JSON_SCHEMA). Train and serve the same shape
    # so the adapter never learns a key the runtime will strip.
    return {
        "arv_estimate": arv,
        "rehab_estimate": rehab,
        "mao_formula": "0.70 * ARV - rehab",
        "mao": mao,
        "verdict": verdict,
        "rationale": (
            f"Contract {int(purchase_price)} {'<=' if verdict == 'Proceed' else '>'} "
            f"MAO {mao} ({spread:+} spread) -> {verdict}."
        ),
    }


# --------------------------------------------------------------------------- #
# Data ingestion
# --------------------------------------------------------------------------- #
def _record_to_messages(record: dict) -> dict:
    """Turn one synthetic contract record into an underwriting training pair.

    user turn   -> raw property data + distress signals (the deal as it arrives)
    assistant   -> strictly the underwriter's logic: ARV prediction, 70%-rule
                   minus rehab, the resulting MAO, and a Proceed/Reject verdict.
    """
    prop = record.get("property") or {}
    contract = record.get("original_contract") or {}

    deal_inputs = {
        "property": prop,
        "deal_terms": contract,
        "distress_signals": _distress_signals(prop, contract),
    }

    user_turn = (
        "Underwrite this wholesale deal. Predict ARV, estimate rehab, apply the "
        "70% rule for the MAO, and return a Proceed/Reject verdict. Return JSON "
        "with keys: arv_estimate, arv_basis, rehab_estimate, rehab_basis, "
        "mao_formula, mao, contract_price, spread_to_mao, verdict, rationale.\n\n"
        + json.dumps(deal_inputs, default=str, indent=2)
    )
    assistant_turn = json.dumps(_underwrite(record), default=str, indent=2)

    return {
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_turn},
            {"role": "assistant", "content": assistant_turn},
        ]
    }


def load_training_dataset(data_path: str, tokenizer):
    """Load the JSONL contract corpus and render it through the chat template."""
    try:
        from datasets import Dataset
    except ImportError as exc:
        raise RuntimeError("datasets is required inside the GPU training image") from exc
    if not os.path.exists(data_path):
        raise FileNotFoundError(f"Training data not found: {data_path}")

    rows = []
    with open(data_path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
                if isinstance(record.get("messages"), list):
                    if record.get("split") == "evaluation":
                        continue
                    rows.append({"messages": record["messages"]})
                else:
                    rows.append(_record_to_messages(record))
            except json.JSONDecodeError:
                # Skip malformed lines rather than abort the whole run.
                continue

    if not rows:
        raise ValueError(f"No usable records parsed from {data_path}")

    dataset = Dataset.from_list(rows)

    def _format(batch):
        texts = [
            tokenizer.apply_chat_template(m, tokenize=False, add_generation_prompt=False)
            for m in batch["messages"]
        ]
        return {"text": texts}

    return dataset.map(_format, batched=True, remove_columns=["messages"])


# --------------------------------------------------------------------------- #
# Training
# --------------------------------------------------------------------------- #
def train(data_path: str, state_code: str, max_steps: int) -> str:
    """Fine-tune the LoRA adapter and export a .gguf. Returns the gguf path."""
    try:
        from unsloth import FastLanguageModel
        from unsloth.chat_templates import get_chat_template
        from trl import SFTTrainer
        from transformers import TrainingArguments
    except ImportError as exc:
        raise RuntimeError(
            "GPU training dependencies are unavailable; submit this manifest to the RunPod training image"
        ) from exc
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=BASE_MODEL,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,            # auto-detect (bf16 on Ampere+, else fp16)
        load_in_4bit=LOAD_IN_4BIT,
    )

    tokenizer = get_chat_template(tokenizer, chat_template="llama-3")

    model = FastLanguageModel.get_peft_model(
        model,
        r=LORA_RANK,
        target_modules=TARGET_MODULES,
        lora_alpha=LORA_ALPHA,
        lora_dropout=0.0,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=3407,
    )

    dataset = load_training_dataset(data_path, tokenizer)

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        dataset_text_field="text",
        max_seq_length=MAX_SEQ_LENGTH,
        packing=False,
        args=TrainingArguments(
            per_device_train_batch_size=2,
            gradient_accumulation_steps=4,
            warmup_steps=5,
            max_steps=max_steps,
            learning_rate=2e-4,
            fp16=not _bf16_supported(),
            bf16=_bf16_supported(),
            logging_steps=1,
            optim="adamw_8bit",
            weight_decay=0.01,
            lr_scheduler_type="linear",
            seed=3407,
            output_dir=os.path.join(OUTPUT_DIR, "checkpoints", state_code.lower()),
            report_to="none",
        ),
    )

    trainer.train()

    # Export a merged, quantized GGUF for edge inference.
    gguf_dir = os.path.join(OUTPUT_DIR, "gguf", state_code.lower())
    os.makedirs(gguf_dir, exist_ok=True)
    model.save_pretrained_gguf(
        gguf_dir,
        tokenizer,
        quantization_method=GGUF_QUANT_METHOD,
    )

    # Also persist the raw LoRA adapter so vLLM can hot-swap it without a merge.
    adapter_dir = os.path.join(OUTPUT_DIR, "adapters", state_code.lower())
    model.save_pretrained(adapter_dir)
    tokenizer.save_pretrained(adapter_dir)

    gguf_path = os.path.join(gguf_dir, f"unsloth.{GGUF_QUANT_METHOD.upper()}.gguf")
    print(f"[edge_forge] GGUF written under: {gguf_dir}")
    print(f"[edge_forge] LoRA adapter written to: {adapter_dir}")
    return gguf_path


def _bf16_supported() -> bool:
    try:
        import torch
        return torch.cuda.is_available() and torch.cuda.is_bf16_supported()
    except Exception:
        return False


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def main():
    parser = argparse.ArgumentParser(description="Edge Forge LoRA trainer")
    parser.add_argument("--state", default="DE", help="State code for the adapter (e.g. DE)")
    parser.add_argument("--data", default=DEFAULT_DATA_PATH, help="Path to JSONL training corpus")
    parser.add_argument("--max-steps", type=int, default=60, help="Training steps")
    parser.add_argument(
        "--style-examples",
        help="Opt-in JSONL examples to redact and train as an agent style adapter",
    )
    parser.add_argument("--agent", help="Agent id owning the consented style examples")
    parser.add_argument("--consent-version", help="Version of the recorded opt-in consent")
    args = parser.parse_args()

    data_path = args.data
    manifest: dict[str, Any] = {
        "dataset_path": data_path,
        "dataset_sha256": artifact_sha256(data_path),
        "kind": "licensed_state_underwriting",
    }
    if args.style_examples:
        if not args.agent or not args.consent_version:
            parser.error("--style-examples requires --agent and --consent-version")
        examples = []
        with open(args.style_examples, "r", encoding="utf-8") as handle:
            for line in handle:
                if line.strip():
                    examples.append(json.loads(line))
        prepared = os.path.join(
            OUTPUT_DIR, "datasets", f"agent-{args.agent}-redacted.jsonl"
        )
        manifest = prepare_consented_style_dataset(
            examples,
            agent_id=args.agent,
            consent_version=args.consent_version,
            output_path=prepared,
        )
        manifest["kind"] = "consented_agent_style"
        data_path = prepared

    gguf_path = train(data_path, args.state, args.max_steps)
    card = build_model_card(
        name=f"{'agent-' + args.agent if args.agent else args.state.lower()}-lora",
        base_model=BASE_MODEL,
        dataset_manifest=manifest,
        metrics={"training_steps": args.max_steps, "evaluation_status": "pending"},
        limitations=["Activation requires a held-out evaluation and canary approval."],
    )
    card_path = Path(gguf_path).with_suffix(".model-card.json")
    card_path.write_text(json.dumps(card, indent=2, sort_keys=True), encoding="utf-8")
    print(f"[edge_forge] Done. Edge artifact: {gguf_path}")
    print(f"[edge_forge] Artifact SHA-256: {artifact_sha256(gguf_path)}")
    print(f"[edge_forge] Model card: {card_path}")


if __name__ == "__main__":
    main()
