"""
Edge Forge — LoRA fine-tuning for state-specific underwriting adapters.

Trains a Llama-3-8B-Instruct LoRA on Delaware wholesale assignment contracts
(generated by synthetic_lawyer.py) using unsloth's 2x-faster 4-bit pipeline,
then exports a quantized .gguf for edge inference via llama.cpp / vLLM.

The resulting adapter is one "state lobe" — hot-swapped at inference time by
EdgeUnderwriter.hot_swap_state_lora() in local_vllm_adapter.py.

Usage:
    python -m backend.ml_forge.edge_forge.train_lora --state DE

Requires (install into the ml_forge venv, GPU recommended):
    pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
    pip install --no-deps trl peft accelerate bitsandbytes
"""

import argparse
import json
import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))

from unsloth import FastLanguageModel
from unsloth.chat_templates import get_chat_template
from datasets import Dataset
from trl import SFTTrainer
from transformers import TrainingArguments

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #
BASE_MODEL = "unsloth/llama-3-8b-Instruct-bnb-4bit"
MAX_SEQ_LENGTH = 4096
LOAD_IN_4BIT = True

# LoRA — adapt only the attention projections, per the edge-forge spec.
LORA_RANK = 16
LORA_ALPHA = 16
TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "o_proj"]

_FORGE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_DATA_PATH = os.path.join(_FORGE_ROOT, "output", "de_assignment_contracts.jsonl")
OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))

# Quantization method for the exported GGUF (q4_k_m balances size/quality).
GGUF_QUANT_METHOD = "q4_k_m"

SYSTEM_PROMPT = (
    "You are an edge underwriting agent for U.S. real estate wholesale deals. "
    "Given raw property data and distress signals, predict the After Repair "
    "Value (ARV), estimate rehab, apply the 70% rule to compute the Maximum "
    "Allowable Offer (MAO = 0.70 * ARV - rehab), and return a Proceed / Reject "
    "verdict as strict JSON."
)

# --------------------------------------------------------------------------- #
# Underwriting model — the synthetic contract records carry deal economics but
# no explicit ARV / rehab / distress fields, so we derive defensible training
# targets from the real property facts. Rough DE resale comps ($/sqft) by
# county feed the ARV estimate.
# --------------------------------------------------------------------------- #
_CURRENT_YEAR = datetime.now().year
_COUNTY_PPSF = {"New Castle": 215.0, "Kent": 175.0, "Sussex": 235.0}
_DEFAULT_PPSF = 200.0
_MAO_RULE = 0.70  # the wholesaler's classic 70% rule


def _round_k(value: float) -> int:
    """Round to the nearest $1,000 — how underwriters actually quote numbers."""
    return int(round(value / 1000.0) * 1000)


def _distress_signals(prop: dict, contract: dict) -> list:
    """Synthesize the deal's distress signals from the property facts. These are
    the *inputs* the model conditions on; the rehab estimate below is causally
    driven by them so the learned chain is internally consistent."""
    signals = []
    year = int(prop.get("year_built") or 0)
    age = _CURRENT_YEAR - year if year else 0

    if age >= 40:
        signals.append(f"Built {year} (~{age}y): roof/HVAC/electrical likely end-of-life")
    elif age >= 25:
        signals.append(f"Built {year} (~{age}y): aging mechanicals, dated finishes")

    contingencies = contract.get("contingencies") or []
    if "inspection" in contingencies:
        signals.append("Inspection contingency active — undisclosed condition risk")

    purchase = float(contract.get("purchase_price") or 0)
    earnest = float(contract.get("earnest_money") or 0)
    if purchase and earnest / purchase < 0.03:
        signals.append("Thin earnest deposit (<3%) — motivated/distressed seller")

    if not signals:
        signals.append("No major distress flags — standard cosmetic turnaround assumed")
    return signals


def _underwrite(record: dict) -> dict:
    """Derive the ARV / rehab / MAO / verdict target for one record."""
    prop = record.get("property") or {}
    contract = record.get("original_contract") or {}

    sqft = float(prop.get("sqft") or 0)
    county = prop.get("county", "")
    year = int(prop.get("year_built") or 0)
    age = _CURRENT_YEAR - year if year else 30
    purchase_price = float(contract.get("purchase_price") or 0)

    ppsf = _COUNTY_PPSF.get(county, _DEFAULT_PPSF)
    arv = _round_k(sqft * ppsf)

    # Rehab budget: $25/sqft cosmetic base, escalated by age-driven distress.
    rehab_psf = 25.0
    if age >= 40:
        rehab_psf += 20.0   # full systems replacement
    elif age >= 25:
        rehab_psf += 10.0   # partial mechanicals + finishes
    if "inspection" in (contract.get("contingencies") or []):
        rehab_psf += 5.0    # contingency reserve for the unknown
    rehab = _round_k(sqft * rehab_psf)

    mao = _round_k(_MAO_RULE * arv - rehab)
    spread = mao - int(purchase_price)
    verdict = "Proceed" if purchase_price and purchase_price <= mao else "Reject"

    # Exactly the 6-key schema the inference engine enforces via guided decoding
    # (local_vllm_adapter.UNDERWRITE_JSON_SCHEMA). Train and serve the same shape
    # so the adapter never learns a key the runtime will strip.
    return {
        "arv_estimate": arv,
        "rehab_estimate": rehab,
        "mao_formula": "0.70 * ARV - rehab",
        "mao": mao,
        "verdict": verdict,
        "rationale": (
            f"Contract {int(purchase_price)} {'<=' if verdict == 'Proceed' else '>'} "
            f"MAO {mao} ({spread:+} spread) -> {verdict}."
        ),
    }


# --------------------------------------------------------------------------- #
# Data ingestion
# --------------------------------------------------------------------------- #
def _record_to_messages(record: dict) -> dict:
    """Turn one synthetic contract record into an underwriting training pair.

    user turn   -> raw property data + distress signals (the deal as it arrives)
    assistant   -> strictly the underwriter's logic: ARV prediction, 70%-rule
                   minus rehab, the resulting MAO, and a Proceed/Reject verdict.
    """
    prop = record.get("property") or {}
    contract = record.get("original_contract") or {}

    deal_inputs = {
        "property": prop,
        "deal_terms": contract,
        "distress_signals": _distress_signals(prop, contract),
    }

    user_turn = (
        "Underwrite this wholesale deal. Predict ARV, estimate rehab, apply the "
        "70% rule for the MAO, and return a Proceed/Reject verdict. Return JSON "
        "with keys: arv_estimate, arv_basis, rehab_estimate, rehab_basis, "
        "mao_formula, mao, contract_price, spread_to_mao, verdict, rationale.\n\n"
        + json.dumps(deal_inputs, default=str, indent=2)
    )
    assistant_turn = json.dumps(_underwrite(record), default=str, indent=2)

    return {
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_turn},
            {"role": "assistant", "content": assistant_turn},
        ]
    }


def load_training_dataset(data_path: str, tokenizer) -> Dataset:
    """Load the JSONL contract corpus and render it through the chat template."""
    if not os.path.exists(data_path):
        raise FileNotFoundError(f"Training data not found: {data_path}")

    rows = []
    with open(data_path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(_record_to_messages(json.loads(line)))
            except json.JSONDecodeError:
                # Skip malformed lines rather than abort the whole run.
                continue

    if not rows:
        raise ValueError(f"No usable records parsed from {data_path}")

    dataset = Dataset.from_list(rows)

    def _format(batch):
        texts = [
            tokenizer.apply_chat_template(m, tokenize=False, add_generation_prompt=False)
            for m in batch["messages"]
        ]
        return {"text": texts}

    return dataset.map(_format, batched=True, remove_columns=["messages"])


# --------------------------------------------------------------------------- #
# Training
# --------------------------------------------------------------------------- #
def train(data_path: str, state_code: str, max_steps: int) -> str:
    """Fine-tune the LoRA adapter and export a .gguf. Returns the gguf path."""
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=BASE_MODEL,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,            # auto-detect (bf16 on Ampere+, else fp16)
        load_in_4bit=LOAD_IN_4BIT,
    )

    tokenizer = get_chat_template(tokenizer, chat_template="llama-3")

    model = FastLanguageModel.get_peft_model(
        model,
        r=LORA_RANK,
        target_modules=TARGET_MODULES,
        lora_alpha=LORA_ALPHA,
        lora_dropout=0.0,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=3407,
    )

    dataset = load_training_dataset(data_path, tokenizer)

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        dataset_text_field="text",
        max_seq_length=MAX_SEQ_LENGTH,
        packing=False,
        args=TrainingArguments(
            per_device_train_batch_size=2,
            gradient_accumulation_steps=4,
            warmup_steps=5,
            max_steps=max_steps,
            learning_rate=2e-4,
            fp16=not _bf16_supported(),
            bf16=_bf16_supported(),
            logging_steps=1,
            optim="adamw_8bit",
            weight_decay=0.01,
            lr_scheduler_type="linear",
            seed=3407,
            output_dir=os.path.join(OUTPUT_DIR, "checkpoints", state_code.lower()),
            report_to="none",
        ),
    )

    trainer.train()

    # Export a merged, quantized GGUF for edge inference.
    gguf_dir = os.path.join(OUTPUT_DIR, "gguf", state_code.lower())
    os.makedirs(gguf_dir, exist_ok=True)
    model.save_pretrained_gguf(
        gguf_dir,
        tokenizer,
        quantization_method=GGUF_QUANT_METHOD,
    )

    # Also persist the raw LoRA adapter so vLLM can hot-swap it without a merge.
    adapter_dir = os.path.join(OUTPUT_DIR, "adapters", state_code.lower())
    model.save_pretrained(adapter_dir)
    tokenizer.save_pretrained(adapter_dir)

    gguf_path = os.path.join(gguf_dir, f"unsloth.{GGUF_QUANT_METHOD.upper()}.gguf")
    print(f"[edge_forge] GGUF written under: {gguf_dir}")
    print(f"[edge_forge] LoRA adapter written to: {adapter_dir}")
    return gguf_path


def _bf16_supported() -> bool:
    try:
        import torch
        return torch.cuda.is_available() and torch.cuda.is_bf16_supported()
    except Exception:
        return False


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def main():
    parser = argparse.ArgumentParser(description="Edge Forge LoRA trainer")
    parser.add_argument("--state", default="DE", help="State code for the adapter (e.g. DE)")
    parser.add_argument("--data", default=DEFAULT_DATA_PATH, help="Path to JSONL training corpus")
    parser.add_argument("--max-steps", type=int, default=60, help="Training steps")
    args = parser.parse_args()

    gguf_path = train(args.data, args.state, args.max_steps)
    print(f"[edge_forge] Done. Edge artifact: {gguf_path}")


if __name__ == "__main__":
    main()
