// @vitest-environment jsdom
/**
 * The interior affordances on the house workspace, and how they describe
 * themselves.
 *
 * Two failures are covered here. The first is that `lead_id` arriving null from
 * the public-record serializer made `useTour` early-return, so no tier badge and
 * no "step inside" ever rendered no matter what had been captured. The second is
 * that a splat generated by the stub provider is walkable but is not this house,
 * and the button that opens it must not say otherwise.
 */

import { cleanup, render, screen } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';

// vitest.config.js does not set `globals: true`, so Testing Library never gets
// to register its automatic afterEach cleanup. Without this every render stays
// in document.body and `screen` queries match across tests — which shows up as
// a confusing "found multiple elements", not as a missing cleanup.
afterEach(cleanup);

const useTour = vi.fn();
vi.mock('../state/useTour', () => ({ useTour: (...args) => useTour(...args) }));
vi.mock('./HouseLinkDialog', () => ({ default: () => null }));

const { default: HouseWorkspace } = await import('./HouseWorkspace');

const HOUSE = {
  id: 'r1',
  address: '1 Main St',
  city: 'Dover',
  state: 'DE',
  lead_id: '22222222-2222-4222-8222-222222222222',
};

function tourPayload(overrides = {}) {
  return {
    best_tier: 3,
    badge: 'Full 3D Walkthrough',
    honest_note: 'Free-roam the actual home in a photoreal 3D reconstruction.',
    walkable_interior: true,
    is_this_property: true,
    splat_url: '/api/media/abc',
    tiers: { exterior: true, photos: false, pano: false, splat: true },
    photo_count: 0,
    floors: [],
    ...overrides,
  };
}

describe('HouseWorkspace interior affordances', () => {
  it('asks the resolver with the lead id the record carries', () => {
    useTour.mockReturnValue({ tour: tourPayload() });

    render(<HouseWorkspace house={HOUSE} />);

    expect(useTour).toHaveBeenCalledWith({ leadId: HOUSE.lead_id });
  });

  it('offers to step inside when the capture is of this property', () => {
    useTour.mockReturnValue({ tour: tourPayload() });

    render(<HouseWorkspace house={HOUSE} />);

    expect(screen.getByRole('button', { name: /step inside/i })).toBeTruthy();
    expect(screen.queryByRole('button', { name: /demo/i })).toBeNull();
  });

  it('says a generated space is not this home', () => {
    useTour.mockReturnValue({
      tour: tourPayload({
        best_tier: 0,
        badge: 'Demo space (not this home)',
        honest_note: 'This walkthrough is a generated demo space, not a capture of this property.',
        is_this_property: false,
        walkable_interior: false,
        tiers: { exterior: true, photos: false, pano: false, splat: false },
      }),
    });

    render(<HouseWorkspace house={HOUSE} />);

    // Still offered — the demo viewer is useful — but never as "step inside".
    expect(screen.getByRole('button', { name: /not this home/i })).toBeTruthy();
    expect(screen.queryByRole('button', { name: /^step inside/i })).toBeNull();
  });

  it('hides the walkable affordance entirely when there is no lead', () => {
    // What the severed chain looked like: no lead id, so the resolver is never
    // called and `tour` stays undefined.
    useTour.mockReturnValue({ tour: undefined });

    render(<HouseWorkspace house={{ ...HOUSE, lead_id: null }} />);

    expect(useTour).toHaveBeenCalledWith({ leadId: null });
    expect(screen.queryByRole('button', { name: /step inside|not this home/i })).toBeNull();
  });
});
